{
    'name': 'Employee Portal',
    'version': '12.0.1.0.0',
    'category': 'website',
    "sequence": 105,
    'summary': 'Project information on website for employees.',
    'description': """In this section employee can see projects and task which is assigned to them and fill their timesheets as well.
                    Also there will be the product entry where employee can add product Id(product's barcode) and process delivery order.""",
    'author': 'Planet Odoo',
    'website': 'http://www.planet-odoo.com/',
    'depends': ['website', 'base', 'project', 'cwl_module', 'stock'],
    'data': [
        'security/access_group.xml',
        'security/ir.model.access.csv',
        'views/template_js.xml',
        'views/template_portal.xml',
        'views/template_employee_form.xml',
        'views/template_thankyou.xml',
        'views/template_timesheet_view_today.xml',
        'views/template_material_form.xml',
        'views/template_product_search_barcode.xml',
        'views/template_product_search_description.xml',
        'views/template_product_search_location.xml',
        'views/template_product_search_by_lot.xml',
    ],
    'qweb': ['static/src/xml/website.backend.xml'],
    'installable': True,
    'application': False,
}
